const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);
function showToast(message){ const t=$('#toast'); t.textContent=message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600); }
function showPage(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id)); window.scrollTo({top:0,behavior:'smooth'}); }
$$('[data-page]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showPage(el.dataset.page)}));
$$('.go-lesson').forEach(b=>b.addEventListener('click',()=>showPage('lesson')));$$('.go-micro').forEach(b=>b.addEventListener('click',()=>showPage('micro')));
function speak(text){ if(!('speechSynthesis' in window)) return showToast('Озвучивание недоступно в этом браузере'); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u); }
document.addEventListener('click',e=>{const b=e.target.closest('[data-say]');if(b)speak(b.dataset.say)});
let lessonStep=1;$('#nextLesson').addEventListener('click',()=>{lessonStep++; if(lessonStep<5){$('.lesson-step i').textContent=`${lessonStep} из 4`;$('.phrase h2').textContent=lessonStep===2?'Can I have it to go?':'Great job!';$('.phrase p').textContent=lessonStep===2?'Можно с собой?':'Отличная работа!';showToast('+8 XP · Фраза изучена');}else{showToast('Урок завершён! +30 XP');showPage('home')}});
const modal=$('#coachModal');function openCoach(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#chatText').focus()}function closeCoach(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#startCoach').addEventListener('click',openCoach);$('#openCoachFromLesson').addEventListener('click',openCoach);$('#closeCoach').addEventListener('click',closeCoach);modal.addEventListener('click',e=>{if(e.target===modal)closeCoach()});
function coachAnswer(input){const chat=$('#chat');const clean=input.trim();if(!clean)return;chat.insertAdjacentHTML('beforeend',`<div class="user-msg">${clean.replace(/</g,'&lt;')}</div>`);let reply='Great choice! Would you like milk or sugar?';let fix='';if(/i want/i.test(clean)){fix='Вежливее: “I’d like …, please.”';reply='Of course! A coffee. Would you like milk or sugar?'}else if(/coffee/i.test(clean)){reply='Great choice! A coffee. Would you like milk or sugar?'}chat.insertAdjacentHTML('beforeend',`${fix?`<div class="correction">✨ ${fix}</div>`:''}<div class="bot-msg">${reply}<button class="listen-msg" data-say="${reply}">🔊</button></div>`);chat.scrollTop=chat.scrollHeight;speak(reply);}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();coachAnswer($('#chatText').value);$('#chatText').value=''});$$('.quick-replies button').forEach(b=>b.addEventListener('click',()=>coachAnswer(b.textContent)));
$('#mic').addEventListener('click',()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return showToast('Голосовой ввод работает в Chrome или Edge');const r=new Recognition();r.lang='en-US';r.onstart=()=>showToast('Слушаю…');r.onresult=e=>{$('#chatText').value=e.results[0][0].transcript;coachAnswer($('#chatText').value);$('#chatText').value=''};r.onerror=()=>showToast('Не удалось распознать речь');r.start()});
let q=1;$$('.answers button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('correct'))return;b.classList.add(b.dataset.correct==='true'?'correct':'');if(b.dataset.correct==='true'){q++;setTimeout(()=>{if(q>10){showToast('Микро-урок завершён! +15 XP');showPage('home');return}$('#quizNumber').textContent=`Вопрос ${q} из 10`;$('#quizBar').style.width=`${q*10}%`;$$('.answers button').forEach(x=>x.classList.remove('correct'));},500)}else showToast('Попробуй ещё раз') }));
$('#freezeInfo').addEventListener('click',()=>showToast('Заморозка серии: 1 шт. · защити один пропущенный день'));
$('#addWord').addEventListener('click',()=>showToast('В прототипе слово добавляется из урока по нажатию на него.'));

// Локальная демонстрация аккаунтов: для рабочего продукта нужны сервер, хэширование паролей и сессии.
const USERS_KEY='lingospark-users', SESSION_KEY='lingospark-session';
const seedUsers=[];
function users(){return JSON.parse(localStorage.getItem(USERS_KEY)||'null')||seedUsers}
function saveUsers(list){localStorage.setItem(USERS_KEY,JSON.stringify(list))}
function session(){const id=localStorage.getItem(SESSION_KEY);return users().find(u=>u.id===id)||null}
function setSession(user){localStorage.setItem(SESSION_KEY,user.id);updateProfile()}
function initial(name){return (name||'Г').trim().charAt(0).toUpperCase()}
function updateProfile(){const user=session();$('#profileName').textContent=user?user.name:'Гость';$('#profileAvatar').textContent=initial(user?.name);$('#profileRole').textContent=user?(user.role==='admin'?'Администратор':'Новичок · A1'):'Войдите в аккаунт';$('.admin-nav').hidden=!user||user.role!=='admin'}
function renderUsers(){const list=users();$('#userTotal').textContent=list.length;$('#studentTotal').textContent=list.filter(u=>u.role==='student').length;$('#usersList').innerHTML=list.map(u=>`<div class="user-row"><div><span class="avatar">${initial(u.name)}</span>${u.name}<small>${u.email}</small></div><span class="role-pill ${u.role==='student'?'student':''}">${u.role==='admin'?'Администратор':'Ученик'}</span><span class="level">${u.level||'A1'}</span>${u.role==='admin'?'<span></span>':`<button class="delete-user" data-id="${u.id}">Удалить</button>`}</div>`).join('')}
const authModal=$('#authModal'), authForm=$('#authForm');let authMode='login', adminCreating=false;
function setAuthMode(mode){authMode=mode;authModal.querySelector('.auth-box').dataset.mode=mode;$$('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));$('#authSubmit').textContent=mode==='login'?'Войти':'Создать аккаунт';$('#authHelp').hidden=false;$('#authHelp').innerHTML=mode==='login'?'Войдите с данными своего аккаунта.':'Первый зарегистрированный аккаунт получает роль <b>администратора</b>.';$('#authName').required=mode==='register';}
function openAuth(mode='login',fromAdmin=false){adminCreating=fromAdmin;setAuthMode(fromAdmin?'register':mode);authModal.classList.add('open');authModal.setAttribute('aria-hidden','false');}
function closeAuth(){authModal.classList.remove('open');authModal.setAttribute('aria-hidden','true');authForm.reset();adminCreating=false}
$('#profileButton').addEventListener('click',()=>openAuth());$('#closeAuth').addEventListener('click',closeAuth);authModal.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.auth)));
authForm.addEventListener('submit',e=>{e.preventDefault();const email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value,name=$('#authName').value.trim();let list=users();if(authMode==='login'){const user=list.find(u=>u.email===email&&u.password===password);if(!user)return showToast('Проверьте email и пароль');setSession(user);closeAuth();showToast(`С возвращением, ${user.name}!`);if(user.role==='admin'){renderUsers();showPage('admin')}return}if(list.some(u=>u.email===email))return showToast('Пользователь с таким email уже есть');const isFirstUser=list.length===0;const user={id:Date.now().toString(),name:name||email.split('@')[0],email,password,role:isFirstUser?'admin':'student',level:isFirstUser?'—':'A1'};list.push(user);saveUsers(list);if(adminCreating){renderUsers();closeAuth();showToast(`Пользователь ${user.name} создан`)}else{setSession(user);closeAuth();showToast(isFirstUser?'Администратор создан. Добро пожаловать!':'Аккаунт создан. Добро пожаловать!')}});
$('#adminAddUser').addEventListener('click',()=>openAuth('register',true));
$('#usersList').addEventListener('click',e=>{const b=e.target.closest('.delete-user');if(!b)return;const list=users().filter(u=>u.id!==b.dataset.id);saveUsers(list);renderUsers();showToast('Пользователь удалён')});
$$('.lesson-choice').forEach(choice=>choice.addEventListener('click',()=>{const d=choice.dataset;$$('.lesson-choice').forEach(x=>x.classList.toggle('selected',x===choice));$('#lessonTitle').textContent=d.title;$('#lessonDesc').textContent=d.desc;$('#lessonPhrase').textContent=d.phrase;$('#lessonTranslation').textContent=d.translation;$('#lessonSpeaker').dataset.say=d.phrase;$('#lessonUnit').textContent=`UNIT 1 · ${d.unit.toUpperCase()}`;$('#lessonCrumb').textContent=[...$$('.lesson-choice')].indexOf(choice)+1;lessonStep=1;$('.lesson-step i').textContent='1 из 4';showToast(`Выбран урок: ${d.title}`)}));
updateProfile();renderUsers();if(!session())setTimeout(()=>openAuth(users().length?'login':'register'),350);
