const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);
function showToast(message){ const t=$('#toast'); t.textContent=message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600); }
function showPage(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id)); window.scrollTo({top:0,behavior:'smooth'}); }
$$('[data-page]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showPage(el.dataset.page)}));
$$('.go-lesson').forEach(b=>b.addEventListener('click',()=>showPage('lesson')));$$('.go-micro').forEach(b=>b.addEventListener('click',()=>showPage('micro')));
function speak(text){ if(!('speechSynthesis' in window)) return showToast('Озвучивание недоступно в этом браузере'); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u); }
document.addEventListener('click',e=>{const b=e.target.closest('[data-say]');if(b)speak(b.dataset.say)});
let lessonStep=1;$('#nextLesson').addEventListener('click',()=>{lessonStep++; if(lessonStep<5){$('.lesson-step i').textContent=`${lessonStep} из 4`;$('.phrase h2').textContent=lessonStep===2?'Can I have it to go?':'Great job!';$('.phrase p').textContent=lessonStep===2?'Можно с собой?':'Отличная работа!';showToast('+8 XP · Фраза изучена');}else{showToast('Урок завершён! +30 XP');showPage('home')}});
const modal=$('#coachModal');function openCoach(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#chatText').focus()}function closeCoach(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#startCoach').addEventListener('click',openCoach);$('#openCoachFromLesson').addEventListener('click',openCoach);$('#closeCoach').addEventListener('click',closeCoach);modal.addEventListener('click',e=>{if(e.target===modal)closeCoach()});
function coachAnswer(input){const chat=$('#chat');const clean=input.trim();if(!clean)return;chat.insertAdjacentHTML('beforeend',`<div class="user-msg">${clean.replace(/</g,'&lt;')}</div>`);let reply='Great choice! Would you like milk or sugar?';let fix='';if(/i want/i.test(clean)){fix='Вежливее: “I’d like …, please.”';reply='Of course! A coffee. Would you like milk or sugar?'}else if(/coffee/i.test(clean)){reply='Great choice! A coffee. Would you like milk or sugar?'}chat.insertAdjacentHTML('beforeend',`${fix?`<div class="correction">✨ ${fix}</div>`:''}<div class="bot-msg">${reply}<button class="listen-msg" data-say="${reply}">🔊</button></div>`);chat.scrollTop=chat.scrollHeight;speak(reply);}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();coachAnswer($('#chatText').value);$('#chatText').value=''});$$('.quick-replies button').forEach(b=>b.addEventListener('click',()=>coachAnswer(b.textContent)));
$('#mic').addEventListener('click',()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return showToast('Голосовой ввод работает в Chrome или Edge');const r=new Recognition();r.lang='en-US';r.onstart=()=>showToast('Слушаю…');r.onresult=e=>{$('#chatText').value=e.results[0][0].transcript;coachAnswer($('#chatText').value);$('#chatText').value=''};r.onerror=()=>showToast('Не удалось распознать речь');r.start()});
let q=1;$$('.answers button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('correct'))return;b.classList.add(b.dataset.correct==='true'?'correct':'');if(b.dataset.correct==='true'){q++;setTimeout(()=>{if(q>10){showToast('Микро-урок завершён! +15 XP');showPage('home');return}$('#quizNumber').textContent=`Вопрос ${q} из 10`;$('#quizBar').style.width=`${q*10}%`;$$('.answers button').forEach(x=>x.classList.remove('correct'));},500)}else showToast('Попробуй ещё раз') }));
$('#freezeInfo').addEventListener('click',()=>showToast('Заморозка серии: 1 шт. · защити один пропущенный день'));
$('#addWord').addEventListener('click',()=>showToast('В прототипе слово добавляется из урока по нажатию на него.'));

// Пользователи и хэши паролей хранятся в SQLite; браузер получает только токен сессии.
const TOKEN_KEY='lingospark-session-token'; let activeUser=null;
async function api(url,options={}){const token=localStorage.getItem(TOKEN_KEY);const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}),...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Ошибка сервера');return data}
function session(){return activeUser}
function setSession(user,token){activeUser=user;if(token)localStorage.setItem(TOKEN_KEY,token);updateProfile()}
function initial(name){return (name||'Г').trim().charAt(0).toUpperCase()}
function updateProfile(){const user=session();$('#profileName').textContent=user?user.name:'Гость';$('#profileAvatar').textContent=initial(user?.name);$('#profileRole').textContent=user?(user.role==='admin'?'Администратор':'Новичок · A1'):'Войдите в аккаунт';$('.admin-nav').hidden=!user||user.role!=='admin'}
async function renderUsers(){try{const list=(await api('/api/users')).users;$('#userTotal').textContent=list.length;$('#studentTotal').textContent=list.filter(u=>u.role==='student').length;$('#usersList').innerHTML=list.map(u=>`<div class="user-row"><div><span class="avatar">${initial(u.name)}</span>${u.name}<small>${u.email}</small></div><span class="role-pill ${u.role==='student'?'student':''}">${u.role==='admin'?'Администратор':'Ученик'}</span><span class="level">${u.level||'A1'}</span>${u.role==='admin'?'<span></span>':`<button class="delete-user" data-id="${u.id}">Удалить</button>`}</div>`).join('')}catch(e){showToast(e.message)}}
const authModal=$('#authModal'), authForm=$('#authForm');let authMode='login', adminCreating=false;
function setAuthMode(mode){authMode=mode;authModal.querySelector('.auth-box').dataset.mode=mode;$$('[data-auth]').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));$('#authSubmit').textContent=mode==='login'?'Войти':'Создать аккаунт';$('#authPassword').minLength=8;$('#authPassword').placeholder='Минимум 8 символов';$('#authHelp').hidden=false;$('#authHelp').innerHTML=mode==='login'?'Войдите с данными своего аккаунта.':'Первый зарегистрированный аккаунт получает роль <b>администратора</b>.';$('#authName').required=mode==='register';}
function openAuth(mode='login',fromAdmin=false){adminCreating=fromAdmin;setAuthMode(fromAdmin?'register':mode);authModal.classList.add('open');authModal.setAttribute('aria-hidden','false');}
function closeAuth(){authModal.classList.remove('open');authModal.setAttribute('aria-hidden','true');authForm.reset();adminCreating=false}
$('#profileButton').addEventListener('click',()=>openAuth());$('#closeAuth').addEventListener('click',closeAuth);authModal.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.auth)));
authForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value,name=$('#authName').value.trim();try{if(authMode==='login'){const data=await api('/api/login',{method:'POST',body:JSON.stringify({email,password})});setSession(data.user,data.token);closeAuth();showToast(`С возвращением, ${data.user.name}!`);if(data.user.role==='admin'){renderUsers();showPage('admin')}return}const data=await api('/api/register',{method:'POST',body:JSON.stringify({name,email,password})});setSession(data.user,data.token);if(adminCreating)await renderUsers();closeAuth();showToast(data.user.role==='admin'?'Администратор создан. Добро пожаловать!':adminCreating?`Пользователь ${data.user.name} создан`:'Аккаунт создан. Добро пожаловать!')}catch(err){showToast(err.message)}});
$('#adminAddUser').addEventListener('click',()=>openAuth('register',true));
$('#usersList').addEventListener('click',async e=>{const b=e.target.closest('.delete-user');if(!b)return;try{await api(`/api/users/${b.dataset.id}`,{method:'DELETE'});await renderUsers();showToast('Пользователь удалён')}catch(err){showToast(err.message)}});
$$('.lesson-choice').forEach(choice=>choice.addEventListener('click',()=>{const d=choice.dataset;$$('.lesson-choice').forEach(x=>x.classList.toggle('selected',x===choice));$('#lessonTitle').textContent=d.title;$('#lessonDesc').textContent=d.desc;$('#lessonPhrase').textContent=d.phrase;$('#lessonTranslation').textContent=d.translation;$('#lessonSpeaker').dataset.say=d.phrase;$('#lessonUnit').textContent=`UNIT 1 · ${d.unit.toUpperCase()}`;$('#lessonCrumb').textContent=[...$$('.lesson-choice')].indexOf(choice)+1;lessonStep=1;$('.lesson-step i').textContent='1 из 4';showToast(`Выбран урок: ${d.title}`)}));
async function bootstrap(){try{const token=localStorage.getItem(TOKEN_KEY);if(token){const data=await api('/api/me');setSession(data.user);if(data.user.role==='admin')renderUsers()}const state=await api('/api/bootstrap');if(!session())setTimeout(()=>openAuth(state.hasUsers?'login':'register'),350)}catch(e){showToast('Запустите сайт через сервер: node server.js')}}
updateProfile();bootstrap();

const THEME_KEY='lingospark-theme';
function applyTheme(theme){const dark=theme==='dark';document.body.classList.toggle('dark',dark);$('#themeToggle').textContent=dark?'☀':'☾';$('#themeToggle').setAttribute('aria-label',dark?'Включить светлую тему':'Включить тёмную тему');}
applyTheme(localStorage.getItem(THEME_KEY)||'light');
$('#themeToggle').addEventListener('click',()=>{const theme=document.body.classList.contains('dark')?'light':'dark';localStorage.setItem(THEME_KEY,theme);applyTheme(theme)});
