const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);
function showToast(message){ const t=$('#toast'); t.textContent=message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600); }
function showPage(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===id)); window.scrollTo({top:0,behavior:'smooth'}); }
$$('[data-page]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showPage(el.dataset.page)}));
$$('.go-lesson').forEach(b=>b.addEventListener('click',()=>showPage('lesson')));$$('.go-micro').forEach(b=>b.addEventListener('click',()=>showPage('micro')));
function speak(text){ if(!('speechSynthesis' in window)) return showToast('Озвучивание недоступно в этом браузере'); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u); }
document.addEventListener('click',e=>{const b=e.target.closest('[data-say]');if(b)speak(b.dataset.say)});
let lessonStep=1;$('#nextLesson').addEventListener('click',()=>{lessonStep++; if(lessonStep<5){$('.lesson-step i').textContent=`${lessonStep} из 4`;$('.phrase h2').textContent=lessonStep===2?'Can I have it to go?':'Great job!';$('.phrase p').textContent=lessonStep===2?'Можно с собой?':'Отличная работа!';showToast('+8 XP · Фраза изучена');}else{showToast('Урок завершён! +30 XP');showPage('home')}});
const modal=$('#coachModal');function openCoach(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#chatText').focus()}function closeCoach(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#startCoach').addEventListener('click',openCoach);$('#openCoachFromLesson').addEventListener('click',openCoach);$('#closeCoach').addEventListener('click',closeCoach);modal.addEventListener('click',e=>{if(e.target===modal)closeCoach()});
function coachAnswer(input){const chat=$('#chat');const clean=input.trim();if(!clean)return;chat.insertAdjacentHTML('beforeend',`<div class="user-msg">${clean.replace(/</g,'&lt;')}</div>`);let reply='Great choice! Would you like milk or sugar?';let fix='';if(/i want/i.test(clean)){fix='Вежливее: “I’d like …, please.”';reply='Of course! A coffee. Would you like milk or sugar?'}else if(/coffee/i.test(clean)){reply='Great choice! A coffee. Would you like milk or sugar?'}chat.insertAdjacentHTML('beforeend',`${fix?`<div class="correction">✨ ${fix}</div>`:''}<div class="bot-msg">${reply}<button class="listen-msg" data-say="${reply}">🔊</button></div>`);chat.scrollTop=chat.scrollHeight;speak(reply);}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();coachAnswer($('#chatText').value);$('#chatText').value=''});$$('.quick-replies button').forEach(b=>b.addEventListener('click',()=>coachAnswer(b.textContent)));
$('#mic').addEventListener('click',()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return showToast('Голосовой ввод работает в Chrome или Edge');const r=new Recognition();r.lang='en-US';r.onstart=()=>showToast('Слушаю…');r.onresult=e=>{$('#chatText').value=e.results[0][0].transcript;coachAnswer($('#chatText').value);$('#chatText').value=''};r.onerror=()=>showToast('Не удалось распознать речь');r.start()});
let q=1;$$('.answers button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('correct'))return;b.classList.add(b.dataset.correct==='true'?'correct':'');if(b.dataset.correct==='true'){q++;setTimeout(()=>{if(q>10){showToast('Микро-урок завершён! +15 XP');showPage('home');return}$('#quizNumber').textContent=`Вопрос ${q} из 10`;$('#quizBar').style.width=`${q*10}%`;$$('.answers button').forEach(x=>x.classList.remove('correct'));},500)}else showToast('Попробуй ещё раз') }));
$('#freezeInfo').addEventListener('click',()=>showToast('Заморозка серии: 1 шт. · защити один пропущенный день'));
$('#addWord').addEventListener('click',()=>showToast('В прототипе слово добавляется из урока по нажатию на него.'));
